'use strict';
const path = require('path');

module.exports = {
    bower: 'bower_components/',
    vendorBase: {
        src: 'app/vendor/',
        dest: 'build/vendor/'
    },
    siteBase: {
        src: 'app/',
        dest: 'build/'
    },
    autoGenerated: {
        dest: 'app/js/autoGenerated'
    },
    karmaConfigFile: path.resolve(__dirname, '../../karma.conf.js')
};
