'use strict';
var configConstants = require('./configConstants');

module.exports = {
    file: {name: 'environmentConstants.js', dest: configConstants.autoGenerated.dest},
    development: {
        marketplaceEntryUrl: 'http://localhost:3005',
        marketplaceInvestorUrl: 'http://localhost:3006',
        marketplaceConsumerUrl: 'http://localhost:3007',
        domain: 'localhost'
    },
    test: {
        marketplaceEntryUrl: 'http://test-entry.stonegateMarketplace.com',
        marketplaceInvestorUrl: 'http://test-investor.stonegateMarketplace.com',
        marketplaceConsumerUrl: 'http://test-consumer.stonegateMarketplace.com',
        domain: 'stonegateMarketplace'
    },
    production: {
        marketplaceEntryUrl: 'http://entry.stonegateMarketplace.com',
        marketplaceInvestorUrl: 'http://investor.stonegateMarketplace.com',
        marketplaceConsumerUrl: 'http://consumer.stonegateMarketplace.com',
        domain: 'stonegateMarketplace'
    }
};